var appVersion = "1.1.8 (11800)";
var langArray  = /(en|pt|de|es|fr|hi|it|in|ja|ko|nl|ro|ru|sv|zh)/;
var lang       = "en";
///////////////////// 
// DETECT LANGUAGE //
///////////////////// http://www.w3schools.com/tags/ref_language_codes.asp
if(window.navigator.language || navigator.userLanguage) {
	lang = (window.navigator.language || navigator.userLanguage).slice(0, 2).toLowerCase();
}
//MANUAL SET (DEV)
if((langArray).test(window.localStorage.getItem("devSetLang"))) { 
	lang = window.localStorage.getItem("devSetLang"); 
}
//SAFETY
if(!lang.match(langArray)) { lang = "en"; }
//#////////////#//
//# LANG ARRAY #//
//#////////////#//
var LANG = {
	LANGUAGE : {
		en : "en",
		pt : "pt",
		de : 'de',
		es : 'es',
		fr : 'fr',
		hi : 'hi',
		it : 'it',
		in : 'in', //id
		ja : 'ja',
		ko : 'ko',
		nl : 'nl',
		ro : 'ro',
		ru : 'ru',
		sv : 'sv',		
		zh : 'zh'	
	},
	LANGUAGE_FULL : {
		en : "en-US",
		pt : "pt-BR",
		de : 'en-US',
		es : 'en-US',
		fr : 'en-US',
		hi : 'en-US',
		it : 'en-US',
		in : 'en-US',
		ja : 'en-US',
		ko : 'en-US',
		nl : 'en-US',
		ro : 'en-US',
		ru : 'en-US',
		sv : 'en-US',		
		zh : 'en-US'	
	},
	CALORIE_COUNTER : {
		en : "Calorie Counter",
		pt : "Contador de Calorias",
		de : 'Kalorienzähler',
		es : 'Contador de calorías',
		fr : 'Compteur de calories',
		hi : 'कैलोरी काउंटर',
		it : 'Contatore calorie',
		in : 'Penghitung Kalori',
		ja : 'カロリー・カウンター',
		ko : '칼로리 카운터',
		nl : 'Calorieteller',
		ro : 'Contor de calorii',
		ru : 'Счётчик калорий',
		sv : 'Kaloriräknare',		
		zh : '卡路里计数器'
	},
	START : {
		en : "start",
		pt : "iniciar",
		de : 'Start',
		es : 'iniciar',
		fr : 'commencer',
		hi : 'प्रारंभ',
		it : 'start',
		in : 'Mulai',
		ja : 'スタート',
		ko : '시작',
		nl : 'start',
		ro : 'începe',
		ru : 'начать',
		sv : 'start',		
		zh : '开始'
	},
	RESET : {
		en : "reset",
		pt : "resetar",
		de : 'Zurücksetzen',
		es : 'reiniciar',
		fr : 'réinitialiser',
		hi : 'रीसेट करें',
		it : 'reset',
		in : 'reset',
		ja : 'リセット',
		ko : '재설정',
		nl : 'reset',
		ro : 'Resetare',
		ru : 'перезагрузка',
		sv : 'återställ',		
		zh : '重置'
	},
	START_DATE : {
		en : "start date",
		pt : "data inicial",
		de : 'Startdatum',
		es : 'fecha de inicio',
		fr : 'date de début',
		hi : 'प्रारंभ की तारीख',
		it : 'data di inizio',
		in : 'tanggal mulai',
		ja : '開始日',
		ko : '시작일',
		nl : 'start datum',
		ro : 'începe data ',
		ru : 'Дата начала',
		sv : 'startdatum',		
		zh : '开始日期'
	},
	APP_INTRO : {
		en : "MyLiveDiet was designed to help you lose weight as easily as possible.",
		pt : "MyLiveDiet foi desenvolvido para ajudá-lo a perder peso de maneira fácil e intuitiva.",
		de : 'MyLiveDiet wurde entwickelt, um Ihnen dabei zu helfen, so einfach wie möglich abzunehmen.',
		es : 'MyLiveDiet ha sido diseñada para ayudarle a perder peso lo más fácilmente posible.',
		fr : 'MyLiveDiet a été conçu pour vous aider à perdre du poids le plus facilement possible.',
		hi : 'MyLiveDiet आपको यथासंभव आसानी सेे अपना वजन कम करने में मदद करने के लिए डिजाइन किया गया है।',
		it : 'MyLiveDiet è stato progettato per aiutare a perdere peso più facilmente possibile.',
		in : 'MyLiveDiet dirancang untuk membantu Anda menurunkan berat badan semudah mungkin.',
		ja : 'MyLiveDietが可能な限り体重を減らすお手伝いをします。',
		ko : 'MyLiveDiet를 사용하면 체중 감량이 한층 더 쉬워집니다.',
		nl : 'MyLiveDiet is ontworpen om u te helpen zo makkelijk mogelijk af te vallen.',
		ro : 'MyLiveDiet a fost conceput pentru a vă ajuta să piardă în greutate la fel de ușor ca possibile.',
		ru : 'Приложение MyLiveDiet разработано, чтобы вы могли сбрасывать вес как можно легче.',
		sv : 'MyLiveDiet är utvecklad för att hjälpa dig gå ner i vikt så enkelt som möjligt.',		
		zh : 'MyLiveDiet被设计为帮助你以最轻松的方法减肥。'
	},
	STEP_1 : {
		en : "Fill your Profile data",
		pt : "Preencha o Perfil",
		de : 'Ihre Profildaten ausfüllen',
		es : 'Rellene los datos de perfil',
		fr : 'Remplissez vos données de profil',
		hi : 'अपने प्रोफ़ाइल डेटा भरें',
		it : 'Compila i dati del tuo Profilo',
		in : 'Isi data Profil Anda',
		ja : 'プロフィールを入力する',
		ko : '프로필 정보 입력',
		nl : 'Vul je profiel gegevens in',
		ro : 'completati datele dvs. de profil',
		ru : 'Заполните свой профиль',
		sv : 'Fyll i dina profiluppgifter',		
		zh : '请填写你的个​​人资料'
	},
	STEP_2 : {
		en : "Hit start",
		pt : "Aperte iniciar",
		de : 'Start drücken',
		es : 'Presione iniciar',
		fr : 'Sélectionnez commencer',
		hi : 'शुरू करें',
		it : 'Premi start',
		in : 'Tekan mulai',
		ja : 'スタートボタンを押す',
		ko : '시작하려면 누르세요.',
		nl : 'Klik start',
		ro : 'lovit începe',
		ru : 'Щёлкните, чтобы начать',
		sv : 'Tryck på start',		
		zh : '点击开始'
	},
	STEP_3 : {
		en : "There is no third step!",
		pt : "Não há terceiro passo!",
		de : 'Das war\'s!',
		es : '¡No hay tercer paso!',
		fr : 'Il n\'y a pas de troisième étape!',
		hi : 'कोई तीसरा कदम नहीं है!',
		it : 'Non esiste un terzo passo!',
		in : 'Tidak ada langkah ketiga!',
		ja : '3番目のステップはありません！',
		ko : '세 번째 단계는 없습니다!',
		nl : 'Er is geen derde stap!',
		ro : 'Nu există nici un al treilea pas!',
		ru : 'Нет третьей ступени!',
		sv : 'Det finns inget tredje steg!',		
		zh : '没有第三步！'
	},
	CLOSE_INTRO : {
		en : "ok, let's get started",
		pt : "ok, vamos começar",
		de : 'Okay, fangen wir an!',
		es : 'ok, vamos a empezar',
		fr : 'ok, on commence',
		hi : 'ठीक है, चलो शुरू करते हैं',
		it : 'ok, cominciamo',
		in : 'oke, ayo kita mulai',
		ja : 'では、始めましょう！',
		ko : '좋아요. 시작합시다.',
		nl : 'ok, laten we beginnen',
		ro : 'ok, hai să începem ',
		ru : 'ok, давайте начнём!',
		sv : 'OK, då börjar vi',		
		zh : '好，让我们开始吧'
	},
	EXERCISE : {
		en : "exercise",
		pt : "exercício",
		de : 'Übung',
		es : 'ejercicio',
		fr : 'exercice',
		hi : 'व्यायाम',
		it : 'esercizio',
		in : 'latihan',
		ja : 'エクササイズ',
		ko : '운동',
		nl : 'beweging',
		ro : 'exercițiu',
		ru : 'Упражнение',
		sv : 'övning',		
		zh : '运动'
	},
	FOOD : {
		en : "food",
		pt : "alimento",
		de : 'Ernährung',
		es : 'comida',
		fr : 'aliment',
		hi : 'भोजन',
		it : 'cibo',
		in : 'makanan',
		ja : '食べ物',
		ko : '음식',
		nl : 'eten',
		ro : 'alimente',
		ru : 'Продукт',
		sv : 'livsmedel',		
		zh : '食物'
	},
	DESCRIPTION : {
		en : "Description...",
		pt : "Descrição...",
		de : 'Beschreibung...',
		es : 'Descripción...',
		fr : 'Description...',
		hi : 'विवरण...',
		it : 'Descrizione...',
		in : 'Deskripsi...',
		ja : '説明...',
		ko : '설명...',
		nl : 'Beschrijving...',
		ro : 'Descriere...',
		ru : 'Описание...',
		sv : 'Beskrivning...',		
		zh : '描述...'
	},
	PRE_FILL : {
		en : "pre-fill",
		pt : "preencher",
		de : 'Vorfüllen',
		es : 'completar',
		fr : 'pré-remplir',
		hi : 'पूर्व भरण',
		it : 'pre-compila',
		in : 'pra-isi',
		ja : '自動入力',
		ko : '자동 채우기',
		nl : 'vooraf invullen',
		ro : 'pre-umplere',
		ru : 'предварительное заполнение',
		sv : 'för-ifyll',		
		zh : '预充'
	},
	ADD_ENTRY : {
		en : "add entry",
		pt : "adicionar",
		de : 'Hinzufügen',
		es : 'añadir',
		fr : 'ajouter',
		hi : 'प्रविष्टि जोड़ें',
		it : 'aggiungere',
		in : 'tambahkan entri',
		ja : 'クイック追加',
		ko : '빠른 추가',
		nl : 'invoer toevoegen',
		ro : 'adăuga intrare',
		ru : 'добавить',
		sv : 'lägg till',		
		zh : '快速添加'
	},
	DELETE : {
		en : "Delete",
		pt : "Apagar",
		de : 'Löschen',
		es : 'Eliminar',
		fr : 'Supprimer',
		hi : 'हटाएँ',
		it : 'Elimina',
		in : 'Hapus',
		ja : '削除',
		ko : '삭제',
		nl : 'Verwijderen',
		ro : 'șterge',
		ru : 'Удалить',
		sv : 'Radera',		
		zh : '删除'
	},
	CLEAR_ALL : {
		en : "clear all",
		pt : "limpar tudo",
		de : 'Alle löschen',
		es : 'eliminar todos',
		fr : 'effacer tout',
		hi : 'सभी साफ़ करें',
		it : 'cancella tutto',
		in : 'hapus semua',
		ja : 'すべてクリア',
		ko : '모두 지우기',
		nl : 'alles wissen',
		ro : 'șterge toate',
		ru : 'очистить всё',
		sv : 'rensa allt',		
		zh : '清除全部'
	},
	ACTIVITY_LOG : {
		en : "activity log",
		pt : "atividades",
		de : 'Aktivitätsprotokoll',
		es : 'registro de actividades',
		fr : 'journal d\'activités',
		hi : 'गतिविधि लॉग',
		it : 'registro delle attività',
		in : 'log aktivitas',
		ja : 'アクティビティログ',
		ko : '활동 기록',
		nl : 'activiteitenlog',
		ro : 'jurnalul de activitate',
		ru : 'Журнал действий',
		sv : 'aktivitets-log',		
		zh : '活动日志'
	},
	FOOD_SEARCH : {
		en : "Food search... (100g)",
		pt : "Buscar alimento... (100g)",
		de : 'Lebensmittelsuche... (100 g)',
		es : 'Buscar comida... (100g)',
		fr : 'Recherche de aliment (100g)',
		hi : 'खाद्य खोज... (100g)',
		it : 'Ricerca di cibo ... (100g)',
		in : 'Pencarian makanan... (100g)',
		ja : '食べ物検索... (100g)', //（100グラム）',
		ko : '음식 검색... (100g)',
		nl : 'Eten zoeken... (100g)',
		ro : 'Căutare de alimente... (100g)',
		ru : 'поиск продуктов (100 г)',
		sv : 'Sök livsmedel... (100 g)',
		zh : '食物搜索... （100克）'
	},
	EXERCISE_SEARCH : {
		en : "Exercise search... (30 min)",
		pt : "Buscar exercício... (30 min)",
		de : 'Übungssuche... (30 Min.)',
		es : 'Buscar ejercicio ... (30 min)',
		fr : 'Recherche d\'exercice (30 min)',
		hi : 'व्यायाम खोज ... (30 मिनट)',
		it : 'Ricerca Esercizio ... (30 min)',
		in : 'Pencarian latihan... (30 menit)',
		ja : 'エクササイズ検索... （30分）',
		ko : '운동 검색... (30분)',
		nl : 'Zoek beweging...(30 min)',
		ro : 'Căutare exercițiu... (30 min)',
		ru : 'Поиск упражнений (30 мин.)',
		sv : 'Sök övning... (30 min)',		
		zh : '运动搜索... （30分钟）'
	},
	NO_ENTRIES : {
		en : "no entries",
		pt : "nenhum registro",
		de : 'Keine Einträge',
		es : 'no hay entradas',
		fr : 'aucune entrée',
		hi : 'कोई प्रविष्टि नहीं',
		it : 'nessuna voce',
		in : 'tak ada entri',
		ja : 'エントリーなし',
		ko : '입력 항목 없음',
		nl : 'geen invoer',
		ro : 'nu există intrări',
		ru : 'Нет записей',
		sv : 'inga poster',		
		zh : '无项目'
	},
	NO_MATCHES : {
		en : "no matches",
		pt : "nenhum resultado",
		de : 'Keine Treffer',
		es : 'Sin coincidencias',
		fr : 'aucune correspondance',
		hi : 'मैचों कोई',
		it : 'nessun risultato',
		in : 'tak ada yang cocok',
		ja : '該当なし',
		ko : '일치 정보 없음',
		nl : 'geen overeenkomsten',
		ro : 'nu există nici un meci',
		ru : 'Соответствий не найдено',
		sv : 'inga matchande',		
		zh : '无匹配'
	},
	PREPARING_DB : {
		en : "preparing database",
		pt : "inicializando",
		de : 'Bereite Datenbank vor...',
		es : 'preparando base de datos',
		fr : 'préparation de la base de données',
		hi : 'डेटाबेस तैयार किया जा रहा है',
		it : 'preparazione del database in corso',
		in : 'menyiapkan basis data',
		ja : 'データベースの準備中',
		ko : '데이터베이스 준비 중',
		nl : 'database aan het voorbereiden',
		ro : 'baza de date pregătește',
		ru : 'создание базы данных',
		sv : 'förbereder databas',		
		zh : '准备数据库'
	},
	MY_FAVOURITES : {
		en : "favourites",
		pt : "favoritos",
		de : 'Favoriten',
		es : 'favoritos',
		fr : 'Favoris',
		hi : 'पसंदीदा',
		it : 'preferiti',
		in : 'favorit',
		ja : 'お気に入り',
		ko : '즐겨찾기',
		nl : 'favorieten',
		ro : 'favorite',
		ru : 'избранное',
		sv : 'favoriter',		
		zh : '我的最爱'
	},
	MY_FOODS : {
		en : "my foods",
		pt : "alimentos",
		de : 'Lebensmittel',
		es : 'comidas',
		fr : 'aliments',
		hi : 'मेरे खाद्य पदार्थ',
		it : 'i miei cibi',
		in : 'makanan saya',
		ja : '食べ物',
		ko : '음식',
		nl : 'mijn eten',
		ro : 'alimentele',
		ru : 'продукты',
		sv : 'mina livsmedel',		
		zh : '我的食物'
	},
	MY_EXERCISES : {
		en : "my exercises",
		pt : "exercícios",
		de : 'Übungen',
		es : 'ejercicios',
		fr : 'exercices',
		hi : 'मेरे व्यायाम',
		it : 'i miei esercizi',
		in : 'latihan saya',
		ja : 'エクササイズ',
		ko : '운동',
		nl : 'mijn beweging',
		ro : 'exercițiile',
		ru : 'упражнения',
		sv : 'mina övningar',		
		zh : '我的运动'
	},
	ADD_NEW_FOOD : {
		en : "add new food",
		pt : "adicionar novo alimento",
		de : 'Neues Lebensmittel hinzufügen',
		es : 'añadir comida',
		fr : 'ajouter un nouvel aliment',
		hi : 'नया खाद्य जोड़ें',
		it : 'aggiungi nuovi alimenti',
		in : 'tambahkan makanan baru',
		ja : '新しい食べ物を追加',
		ko : '새 음식 추가',
		nl : 'nieuw eten toevoegen',
		ro : 'adăuga noi alimente',
		ru : 'Добавить новый продукт',
		sv : 'lägg till nytt livsmedel',		
		zh : '添加新的食物'
	},
	ADD_NEW_EXERCISE : {
		en : "add new exercise",
		pt : "adicionar novo exercício",
		de : 'Neue Übung hinzufügen',
		es : 'añadir ejercicio',
		fr : 'ajouter un nouvel exercice',
		hi : 'नया व्यायाम जोड़ें',
		it : 'aggiungi nuovo esercizio',
		in : 'tambahkan latihan baru',
		ja : '新しいエクササイズを追加',
		ko : '새 운동 추가',
		nl : 'nieuwe beweging toevoegen',
		ro : 'adăuga noi exercițiu',
		ru : 'Добавить новое упражнение',
		sv : 'lägg till ny övning',		
		zh : '添加新的运动'
	},
	ADD : {
		en : "add",
		pt : "adicionar",
		de : 'Hinzufügen',
		es : 'añadir',
		fr : 'ajouter',
		hi : 'जोड़ें',
		it : 'aggiungi',
		in : 'tambahkan',
		ja : '追加',
		ko : '추가',
		nl : 'toevoegen',
		ro : 'adăuga',
		ru : 'добавить',
		sv : 'lägg till',		
		zh : '添加'
	},
	SAVE : {
		en : "save",
		pt : "salvar",
		de : 'Speichern',
		es : 'guardar',
		fr : 'enregistrer',
		hi : 'सहेजें',
		it : 'salva',
		in : 'simpan',
		ja : '保存',
		ko : '저장',
		nl : 'opslaan',
		ro : 'salva',
		ru : 'сохранить',
		sv : 'spara',		
		zh : '保存'
	},
	ADD_NAME : {
		en : "Name",
		pt : "Nome",
		de : 'Name',
		es : 'Nombre',
		fr : 'Nom',
		hi : 'नाम',
		it : 'Nome',
		in : 'Nama',
		ja : '名前',
		ko : '이름',
		nl : 'Naam',
		ro : 'Nume',
		ru : 'Название',
		sv : 'Namn',		
		zh : '名称'
	},
	ADD_AMOUNT : {
		en : "Amount",
		pt : "Quantidade",
		de : 'Menge',
		es : 'Cantidad',
		fr : 'Quantité',
		hi : 'मात्रा',
		it : 'Quantità',
		in : 'kuantitas',
		ja : '総量',
		ko : '양',
		nl : 'hoeveelheid',
		ro : 'Cantitate',
		ru : 'Количество',
		sv : 'Belopp',		
		zh : '数量'
	},
	ADD_DURATION : {
		en : "Duration",
		pt : "Duração",
		de : 'Dauer',
		es : 'Duración',
		fr : 'Durée',
		hi : 'अवधि',
		it : 'Durata',
		in : 'Durasi',
		ja : '期間',
		ko : '기간',
		nl : 'Duur',
		ro : 'Durată',
		ru : 'Продолжительность',
		sv : 'varaktighet',		
		zh : '持续时间'
	},
	DELETE_ITEM : {
		en : "Delete item",
		pt : "Excluir item",
		de : 'Artikel löschen',
		es : 'Eliminar elemento',
		fr : 'Supprimer l\'élément',
		hi : 'आइटम हटाएँ',
		it : 'Elimina voce',
		in : 'Hapus item',
		ja : 'アイテムを削除',
		ko : '아이템 삭제',
		nl : 'Verwijder item',
		ro : 'Ștergeți elementul',
		ru : 'Удалить элемент',
		sv : 'Radera post',		
		zh : '删除项目'
	},
	CALORIES_AVALIABLE : {
		en : "avaliable calories",
		pt : "calorias disponíveis",
		de : 'Verfügbare Kalorien',
		es : 'calorías disponibles',
		fr : 'calories disponibles',
		hi : 'उपलब्ध कैलोरी',
		it : 'calorie disponibili',
		in : 'kalori yang tersedia',
		ja : '利用可能なカロリー',
		ko : '가능 칼로리',
		nl : 'calorieën beschikbaar',
		ro : 'calorii disponibile',
		ru : 'калорий доступно',
		sv : 'tillgängliga kalorier',		
		zh : '包含的卡路里'
	},
	DAILY_CALORIES : {
		en : "daily calories",
		pt : "calorias por dia",
		de : 'Tägliche Kalorien',//Kalorien pro Tag
		es : 'calorías diarias',
		fr : 'kcal / jour', //'calories quotidiennes',
		hi : 'दैदैनिक कैलोरी',
		it : 'calorie al giorno',
		in : 'kalori harian',
		ja : '毎日のカロリー',
		ko : '하루 칼로리',
		nl : 'dagelijkse calorieën',
		ro : 'calorii pe zi',
		ru : 'калорий в день',
		sv : 'dagliga kalorier',		
		zh : '每日的卡路里'
	},
	CALORIC_INTAKE : {
		en : "caloric intake",
		pt : "ingestão calórica",
		de : 'Kalorienaufnahme',
		es : 'ingesta de calorías',
		fr : 'apport calorique',
		hi : 'गरमी सेवन',
		it : 'apporto calorico',
		in : 'masukan kalori',
		ja : 'カロリー摂取量',
		ko : '칼로리 섭취',
		nl : 'calorie-inname',
		ro : 'aportul caloric',
		ru : 'потребление калорий',
		sv : 'kaloriintag',		
		zh : '摄入卡路里'
	},
	WEIGHT_LOSS : {
		en : "weight loss",
		pt : "perda de peso",
		de : 'Gewichtsverlust',
		es : 'pérdida de peso',
		fr : 'perte de poids',
		hi : 'वजन घटाने',
		it : 'perdita di peso',
		in : 'penurunan berat badan',
		ja : '減量',
		ko : '체중 감량',
		nl : 'gewichtsverlies',
		ro : 'pierderea în greutate',
		ru : 'потеря веса',
		sv : 'viktminskning',		
		zh : '体重减少'
	},
	TIME_ELAPSED : {
		en : "elapsed time",
		pt : "tempo total",
		de : 'Verstrichene Zeit',
		es : 'tiempo transcurrido',
		fr : 'temps écoulé',
		hi : 'बीता समय',
		it : 'tempo trascorso',
		in : 'waktu berlalu',
		ja : '経過時間',
		ko : '시간 경과',
		nl : 'verstreken tijd',
		ro : 'timpul scurs',
		ru : 'Прошло времени',
		sv : 'förfluten tid',		
		zh : '经过的时间'
	},
	CALORIC_BALANCE : {
		en : "caloric balance",
		pt : "balanço calórico",
		de : 'Kalorienbilanz',
		es : 'equilibrio calórico',
		fr : 'équilibre calorique',
		hi : 'गरमी संतुलन',
		it : 'equilibrio calorico',
		in : 'keseimbangan kalori',
		ja : 'カロリー収支',
		ko : '칼로리 밸런스',
		nl : 'calorie balans',
		ro : 'echilibru caloric',
		ru : 'баланс калорий',
		sv : 'caloric balans',		
		zh : '热量平衡'
	},
	SURPLUS : {
		en : "surplus",
		pt : "excesso",
		de : 'Überschuss',
		es : 'exceso',
		fr : 'excédent',
		hi : 'अधिशेष',
		it : 'in più',
		in : 'kelebihan',
		ja : '余剰',
		ko : '너무 많음',
		nl : 'overschot',
		ro : 'surplus',
		ru : 'излишек',
		sv : 'överskott',		
		zh : '盈余'
	},
	DEFICIT : {
		en : "deficit",
		pt : "déficit",
		de : 'Defizit',
		es : 'déficit',
		fr : 'déficit',
		hi : 'घाटा',
		it : 'in meno',
		in : 'defisit',
		ja : '不足',
		ko : '부족',
		nl : 'tekort',
		ro : 'deficit',
		ru : 'недостаток',
		sv : 'underskott',		
		zh : '赤字'
	},
	BALANCED : {
		en : "balanced",
		pt : "balanceado",
		de : 'Ausgeglichen',
		es : 'equilibrado',
		fr : 'equilibrato',
		hi : 'संतुलित',
		it : 'bilanciato',
		in : 'seimbang',
		ja : 'バランスの取れた',
		ko : '균형',
		nl : 'evenwichtige',
		ro : 'echilibrat',
		ru : 'сбалансированная',
		sv : 'balanserad',		
		zh : '均衡'
	},
	MENU_STATUS : {
		en : "status",
		pt : "status",
		de : 'Status',
		es : 'estado',
		fr : 'statut',
		hi : 'हैसियत',
		it : 'stato',
		in : 'status',
		ja : 'ステータス',
		ko : '상태',
		nl : 'status',
		ro : 'status',
		ru : 'Состояние',
		sv : 'status',		
		zh : '状态'
	},
	MENU_DIARY : {
		en : "diary",
		pt : "diário",
		de : 'Tagebuch',
		es : 'diario',
		fr : 'journal',
		hi : 'डायरी',
		it : 'diario',
		in : 'buku harian',
		ja : '日記',
		ko : '일기',
		nl : 'dagboek',
		ro : 'jurnal',
		ru : 'Дневник',
		sv : 'dagbok',		
		zh : '日志'
	},
	MENU_PROFILE : {
		en : "profile",
		pt : "perfil",
		de : 'Profil',
		es : 'perfil',
		fr : 'profil',
		hi : 'प्रोफाइल',
		it : 'profilo',
		in : 'profil',
		ja : 'プロフィール',
		ko : '프로필',
		nl : 'profiel',
		ro : 'profil',
		ru : 'профиль',
		sv : 'profil',		
		zh : '资料'
	},
	MENU_SETTINGS : {
		en : "settings",
		pt : "configurar",
		de : 'Einstellungen',
		es : 'ajustes',
		fr : 'paramètres',
		hi : 'सेटिंग्स',
		it : 'Impostazioni',
		in : 'pengaturan',
		ja : '設定',
		ko : '설정',
		nl : 'instellingen',
		ro : 'Setările',
		ru : 'настройки',
		sv : 'inställningar',		
		zh : '设置'
	},
	NOW : {
		en : "now",
		pt : "agora",
		de : 'jetzt',
		es : 'ahora',
		fr : 'maintenant',
		hi : 'अब',
		it : 'ora',
		in : 'sekarang',
		ja : '今',
		ko : '현재',
		nl : 'nu',
		ro : 'acum',
		ru : 'Сейчас',
		sv : 'nu',		
		zh : '现在'
	},
	TODAY : {
		en : "today",
		pt : "hoje",
		de : 'heute',
		es : 'hoy',
		fr : 'aujourd\'hui',
		hi : 'आज',
		it : 'oggi',
		in : 'hari ini',
		ja : '今日',
		ko : '오늘',
		nl : 'vandaag',
		ro : 'azi',
		ru : 'сегодня',
		sv : 'idag',		
		zh : '今天'
	},
	MINUTE : {
		en : "minute",
		pt : "minuto",
		de : 'Minute',
		es : 'minuto',
		fr : 'minute',
		hi : 'मिनट',
		it : 'minuto',
		in : 'menit',
		ja : '分',
		ko : '분',
		nl : 'minuut',
		ro : 'minut',
		ru : 'минуту',
		sv : 'minut',		
		zh : '分钟'
	},
	MINUTES : {
		en : "minutes",
		pt : "minutos",
		de : 'Minuten',
		es : 'minutos',
		fr : 'minutes',
		hi : 'मिनट',
		it : 'minuti',
		in : 'menit',
		ja : '分',
		ko : '분',
		nl : 'minuten',
		ro : 'minute',
		ru : 'минут',
		sv : 'minuter',		
		zh : '分钟'
	},
	MIN : {
		en : "min",
		pt : "min",
		de : 'Min',
		es : 'min',
		fr : 'min',
		hi : 'मिनट',
		it : 'min',
		in : 'men',
		ja : '分',
		ko : '분',
		nl : 'min',
		ro : 'min',
		ru : 'мин.',
		sv : 'min',		
		zh : '分钟'
	},
	HOUR : {
		en : "hour",
		pt : "hora",
		de : 'Stunde',
		es : 'hora',
		fr : 'heure',
		hi : 'घंटा',
		it : 'ora',
		in : 'jam',
		ja : '時間',
		ko : '시간',
		nl : 'uur',
		ro : 'oră',
		ru : 'час',
		sv : 'timme',		
		zh : '小时'
	},
	HOURS : {
		en : "hours",
		pt : "horas",
		de : 'Stunden',
		es : 'horas',
		fr : 'heures',
		hi : 'घंटे',
		it : 'ore',
		in : 'jam',
		ja : '時間',
		ko : '시간',
		nl : 'uren',
		ro : 'ore',
		ru : 'часов',
		sv : 'timmar',		
		zh : '小时'
	},
	DAY : {
		en : "day",
		pt : "dia",
		de : 'Tag',
		es : 'día',
		fr : 'jour',
		hi : 'दिन',
		it : 'giorno',
		in : 'hari',
		ja : '日',
		ko : '일',
		nl : 'dag',
		ro : 'zi',
		ru : 'день',
		sv : 'dag',		
		zh : '天'
	},
	DAYS : {
		en : "days",
		pt : "dias",
		de : 'Tage',
		es : 'días',
		fr : 'jours',
		hi : 'दिन',
		it : 'giorni',
		in : 'hari',
		ja : '日',
		ko : '일',
		nl : 'dagen',
		ro : 'zile',
		ru : 'дней',
		sv : 'dagar',		
		zh : '天'
	},
	AND : {
		en : "and",
		pt : "e",
		de : 'und',
		es : 'y',
		fr : 'et',
		hi : 'और',
		it : 'e',
		in : 'dan',
		ja : 'と',
		ko : '및',
		nl : 'en',
		ro : 'și',
		ru : 'и',
		sv : 'och',		
		zh : '和'
	},
	AGO : {
		en : "ago",
		pt : "atrás",
		de : '',
		es : '',
		fr : '',
		hi : 'पूर्व',
		it : 'fa',
		in : 'lalu',
		ja : '前',
		ko : '전',
		nl : 'geleden',
		ro : 'în urma',
		ru : 'назад',
		sv : 'sedan',		
		zh : '前'
	},
	PREAGO : {
		en : "",
		pt : "",
		de : 'vor',
		es : 'hace',
		fr : 'il y a',
		hi : '',
		it : '',
		in : '',
		ja : '',
		ko : '',
		nl : '',
		ro : '',
		ru : '',
		sv : '', //för		
		zh : ''
	},	
	CALORIE : {
		en : "calorie",
		pt : "caloria",
		de : 'Kalorie',
		es : 'caloría',
		fr : 'calorie',
		hi : 'कैलोरी',
		it : 'caloria',
		in : 'kalori',
		ja : 'カロリー',
		ko : '칼로리',
		nl : 'calorie',
		ro : 'calorie',
		ru : 'калория',
		sv : 'kalori',		
		zh : '卡路里'
	},
	CALORIES : {
		en : "calories",
		pt : "calorias",
		de : 'Kalorien',
		es : 'calorías',
		fr : 'calories',
		hi : 'कैलोरी',
		it : 'calorie',
		in : 'kalori',
		ja : 'カロリー',
		ko : '칼로리',
		nl : 'calorieën',
		ro : 'calorii',
		ru : 'калорий.',
		sv : 'kalorier',		
		zh : '卡路里'
	},	
	KCAL : {
		en : "kcal",
		pt : "kcal",
		de : 'kcal',
		es : 'kcal',
		fr : 'kcal',
		hi : 'कैलोरी',
		it : 'kcal',
		in : 'kkal',
		ja : 'カロリー', //キロカロリー
		ko : '칼로리',  //킬로칼로리
		nl : 'kcal',
		ro : 'kcal',
		ru : 'ккал',
		sv : 'kcal',		
		zh : '千卡'   //千卡
	},	
	CENTIMETERS : {
		en : "centimeters",
		pt : "centímetros",
		de : 'Zentimeter',
		es : 'centímetros',
		fr : 'centimètres',
		hi : 'सेंटीमीटर',
		it : 'centimetri',
		in : 'sentimeter',
		ja : 'センチ',
		ko : '센티미터',
		nl : 'centimeters',
		ro : 'centimetri',
		ru : 'сантиметров',
		sv : 'centimeter',		
		zh : '厘米'
	},
	FEET_INCHES : {
		en : "feet/inches",
		pt : "pés/pol.",
		de : 'Fuß/Zoll',
		es : 'pies/pul.',
		fr : 'pieds/pouces',
		hi : 'फुट / इंच',
		it : 'piedi/pollici',
		in : 'kaki/inci',
		ja : 'フィート/インチ',
		ko : '피트/인치',
		nl : 'feet/inches',
		ro : 'picioare / inch',
		ru : 'Футов/дюймов',
		sv : 'fot/tum',		
		zh : '英尺/英寸'
	},
	GRAMS : {
		en : "grams",
		pt : "gramas",
		de : 'Gramm',
		es : 'gramos',
		fr : 'grammes',
		hi : 'ग्राम',
		it : 'grammi',
		in : 'gram',
		ja : 'グラム',
		ko : '그램',
		nl : 'grammen',
		ro : 'grame',
		ru : 'граммов',
		sv : 'gram',		
		zh : '克'
	},
	G : {
		en : "g",
		pt : "g",
		de : 'g',
		es : 'g',
		fr : 'g',
		hi : 'ग्राम',
		it : 'g',
		in : 'g',
		ja : 'g', //'グラム',
		ko : 'g', //'그램',
		nl : 'g',
		ro : 'g',
		ru : 'г', 
		ru : 'g', 
		zh : '克'
	},	
	KILOGRAMS : {
		en : "kilograms",
		pt : "kilogramas",
		de : 'Kilogramm',
		es : 'kilogramos',
		fr : 'kilogrammes',
		hi : 'किलोग्राम',
		it : 'chilogrammi',
		in : 'kilogram',
		ja : 'キロ',
		ko : '킬로그램',
		nl : 'kilogrammen',
		ro : 'kilograme',
		ru : 'килограммов',
		sv : 'kilogram',		
		zh : '公斤'
	},
	KG : {
		en : "kg",
		pt : "kg",
		de : 'kg',
		es : 'kg',
		fr : 'kg',
		hi : 'किग्रा',
		it : 'kg',
		in : 'kg',
		ja : 'キロ.',
		ko : '킬로그램',
		nl : 'kg',
		ro : 'kg',
		ru : 'кг', 
		sv : 'kg',
		zh : '公斤'
	},
	POUNDS : {
		en : "pounds",
		pt : "libras",
		de : 'Pfund',
		es : 'libras',
		fr : 'livres',
		hi : 'पाउंड',
		it : 'sterline',
		in : 'pound',
		ja : 'ポンド',
		ko : '파운드',
		nl : 'ponden',
		ro : 'livre',
		ru : 'фунтов',
		sv : 'pund',		
		zh : '磅'
	},
	LB : {
		en : "lb",
		pt : "lb",
		de : 'lb',
		es : 'lb',
		fr : 'lb',
		hi : 'पौंड',
		it : 'lb',
		in : 'lb',
		ja : 'ポンド',
		ko : '파운드',
		nl : 'lb',
		ro : 'lb',
		ru : 'фунтов', 
		sv : 'lb',
		zh : '磅'
	},
	PROTEINS : {
		en : "Proteins",
		pt : "Proteínas",
		de : 'Proteine',
		es : 'Proteinas',
		fr : 'Protéines',
		hi : 'प्रोटीन',
		it : 'Proteine',
		in : 'Protein',
		ja : 'タンパク質',
		ko : '단백질',
		nl : 'Eiwitten',
		ro : 'proteine',
		ru : 'белки',
		sv : 'Proteiner',		
		zh : '蛋白质'
	},
	CARBS : {
		en : "carbohydrates",
		pt : "Carboidratos",
		de : 'Kohlenhydrate',
		es : 'Carbohidratos',
		fr : 'Glucides',
		hi : 'कार्बो',
		it : 'Carboidrati',
		in : 'Karbo',
		ja : '炭水化物',
		ko : '탄수화물',
		nl : 'Koolhydraten',
		ro : 'Carbohidratii',
		ru : 'Углеводы',
		sv : 'Kolhydrater',		
		zh : '碳水化合物'
	},
	FATS : {
		en : "Fats",
		pt : "Gorduras",
		de : 'Fette',
		es : 'Grasas',
		fr : 'Graisses',
		hi : 'वसा',
		it : 'Grassi',
		in : 'Lemak',
		ja : '脂肪',
		ko : '지방',
		nl : 'Vetten',
		ro : 'grăsimi',
		ru : 'Жиры',
		sv : 'Fetter',		
		zh : '脂肪'
	},
	PRO : {
		en : "pro",
		pt : "pro",
		de : 'Pro',
		es : 'pro',
		fr : 'pro',
		hi : 'प्रोटीन',
		it : 'pro',
		in : 'pro',
		ja : 'タンパク',
		ko : '단백질',
		nl : 'eiw',
		ro : 'pro',
		ru : 'белок',
		sv : 'pro',		
		zh : '蛋白质'
	},
	CAR : {
		en : "car",
		pt : "car",
		de : 'Kol',
		es : 'car',
		fr : 'glu',
		hi : 'कार्बो',
		it : 'car',
		in : 'kar',
		ja : '炭水化物',
		ko : '탄수화물',
		nl : 'kh',
		ro : 'car',
		ru : 'углевод',
		sv : 'kh',		
		zh : '糖类'
	},
	FAT : {
		en : "fat",
		pt : "gor",
		de : 'Fet',
		es : 'gra',
		fr : 'gra',
		hi : 'वसा',
		it : 'gra',
		in : 'lemak',
		ja : '脂肪',
		ko : '지방',
		nl : 'vet',
		ro : 'gră',
		ru : 'жир',
		sv : 'fett',		
		zh : '脂肪'
	},
	ARE_YOU_SURE : {
		en : "are you sure?",
		pt : "confirmar?",
		de : 'Sind Sie sicher?',
		es : '¿está seguro?',
		fr : 'Vraiment?',
		hi : 'क्या आप वाकई ऐसा करना चाहते हैं?',
		it : 'sei sicuro?',
		in : 'Anda yakin?',
		ja : 'よろしいですか？',
		ko : '정말입니까?',
		nl : 'weet je het zeker?',
		ro : 'ești sigur?',
		ru : 'Вы уверены?',
		sv : 'är du säker?',		
		zh : '你确定吗？'
	},
	OK : {
		en : "ok",
		pt : "ok",
		de : 'ok',
		es : 'ok',
		fr : 'ok',
		hi : 'ठीक',
		it : 'ok',
		in : 'oke',
		ja : 'ok',
		ko : '확인',
		nl : 'ok',
		ro : 'ok',
		ru : 'ok',
		sv : 'ok',		
		zh : '好'
	},
	CANCEL : {
		en : "cancel",
		pt : "cancelar",
		de : 'Abbrechen',
		es : 'cancelar',
		fr : 'annuler',
		hi : 'रद्द करें',
		it : 'annulla',
		in : 'batalkan',
		ja : 'キャンセル',
		ko : '취소',
		nl : 'annuleren',
		ro : 'anula',
		ru : 'отмена',
		sv : 'ångra',		
		zh : '取消'
	},
	SETTINGS_WIPE : {
		en : "Reset settings",
		pt : "Apagar configurações",
		de : 'Einstellungen zurücksetzen',
		es : 'Restablecer configuración',
		fr : 'Réinitialiser les paramètres',
		hi : 'सेटिंग्स रीसेट करें',
		it : 'Ripristinare le impostazioni',
		in : 'Pengaturan reset',
		ja : '設定のリセット',
		ko : '재설정',
		nl : 'Reset instellingen',
		ro : 'Reseta setările',
		ru : 'Сбросить настройки',
		sv : 'Återställ inställningar',		
		zh : '重新设置'
	},
	SETTINGS_WIPE_TITLE : {
		en : "all data will be erased",
		pt : "todos os dados serão apagados",
		de : 'Alle Daten werden gelöscht',
		es : 'Toda la información será eliminada',
		fr : 'toutes les données seront effacées',
		hi : 'सभी डेटा मिट जाएगा',
		it : 'tutti i dati saranno cancellati',
		in : 'semua data akan dihapus',
		ja : 'すべてのデータが消去されます',
		ko : '모든 데이터가 삭제됩니다.',
		nl : 'alle data zal verwijderd worden',
		ro : 'toate datele vor fi șterse',
		ru : 'Все данные будут удалены',
		sv : 'alla data kommer att raderas',		
		zh : '所有数据都将被删除'
	},
	NOT_RUNNING_TITLE : {
		en : "The counter is currently stopped",
		pt : "O contador não está ativado",
		de : 'Der Zähler läuft derzeit nicht',
		es : 'El contador está parado',
		fr : 'Le compteur est actuellement arrêté',
		hi : 'काउंटर फिलहाल बंद कर दिया गया है',
		it : 'Il contatore è attualmente fermo',
		in : 'Penghitung saat ini dihentikan',
		ja : '現在、カウンターは停止中',
		ko : '현재 카운터가 멈춰있습니다.',
		nl : 'De teller is momenteel gestopt',
		ro : 'Contorul este oprit',
		ru : 'В данный момент счётчик не работает.',
		sv : 'Räknaren är stoppad för närvarande',		
		zh : '计数器现已停止'
	},
	NOT_RUNNING_DIALOG : {
		en : "Would you like to start it now?",
		pt : "Gostaria de iniciá-lo agora?",
		de : 'Möchten Sie es jetzt beginnen?',
		es : '¿Le gustaría empezar ahora?',
		fr : 'Voulez-vous le lancer maintenant ?',
		hi : 'अब आप इसे शुरू करना चाहेंगे?',
		it : 'Vuoi avviarlo ora?',
		in : 'Anda ingin memulainya sekarang?',
		ja : '今すぐ始めますか？',
		ko : '지금 시작하겠습니까?',
		nl : 'Wil je deze nu starten?',
		ro : 'Doriți să-l înceapă acum?',
		ru : 'Хотите запустить его сейчас?',
		sv : 'Vill du starta den nu?',		
		zh : '你想现在开始?'
	},
	ABOUT_TITLE : {
		en : "MyLiveDiet v" + appVersion,
		pt : "MyLiveDiet v" + appVersion,
		de : "MyLiveDiet v" + appVersion,
		es : "MyLiveDiet v" + appVersion,
		fr : "MyLiveDiet v" + appVersion,
		hi : "MyLiveDiet v" + appVersion,
		it : "MyLiveDiet v" + appVersion,
		in : "MyLiveDiet v" + appVersion,
		ja : "MyLiveDiet v" + appVersion,
		ko : "MyLiveDiet v" + appVersion,
		ro : "MyLiveDiet v" + appVersion,
		ru : "MyLiveDiet v" + appVersion,
		zh : "MyLiveDiet v" + appVersion
	},
	ABOUT_DIALOG : {
		en : "Developed by André Cancian",
		pt : "Desenvolvido por André Cancian",
		de : 'Entwickelt von André Cancian',
		es : 'Desarrollado por André Cancian',
		fr : 'Développé par André Cancian',
		hi : 'आंद्रे कैनसियन द्वारा विकसित',
		it : 'Sviluppato da André Cancian',
		in : 'Dikembangkan oleh André Cancian',
		ja : 'André Cancian開発',
		ko : '개발자: André Cancian',
		nl : 'Ontwikkeld door André Cancian',
		ro : 'Dezvoltat de André Cancian',
		ru : 'РРазработано Андре Канчиан',
		sv : 'Utvecklad av André Cancian',		
		zh : '由AndréCancian开发'
	},
	RESET_COUNTER_TITLE : {
		en : "reset counter",
		pt : "reiniciar contador",
		de : 'Zähler zurücksetzen',
		es : 'reiniciar contador',
		fr : 'réinitialiser le compteur',
		hi : 'काउंटर रीसेट करें',
		it : 'azzera il contatore',
		in : 'reset penghitung',
		ja : 'カウンターのリセット',
		ko : '카운터 재설정',
		nl : 'reset teller',
		ro : 'reseta counter',
		ru : 'Перезагрузить счётчик',
		sv : 'återställ räknaren',		
		zh : '重置计数器'
	},
	RESET_ENTRY_TITLE : {
		en : "Reset entry value",
		pt : "Resetar entrada",
		de : 'Eingabewert zurücksetzen',
		es : 'Restablecer valor introducido',
		fr : 'Réinitialiser la valeur d\'entrée',
		hi : 'प्रविष्टि मान रीसेट करें',
		it : 'Ripristina valore di iscrizione',
		in : 'Reset nilai entri',
		ja : 'エントリ値のリセット',
		ko : '입력값 재설정',
		nl : 'Reset invoerwaarde',
		ro : 'Reset valoare de intrare',
		ru : 'Сброс значения записи',
		sv : 'Återställ ingångsvärdet',		
		zh : '重置输入的值'
	},
	BLANK_FIELD_TITLE : {
		en : "Required fields have been left blank.",
		pt : "Campos obrigatórios foram deixados em branco.",
		de : 'Erforderliche Felder sind leer geblieben.',
		es : 'Los campos obligatorios están en blanco.',
		fr : 'Des champs obligatoires sont vides.',
		hi : 'आवश्यक फ़ील्ड रिक्त छोड़ दिया गया है।',
		it : 'I campi obbligatori sono stati lasciati in bianco.',
		in : 'Bidang yang harus diisi dibiarkan kosong.',
		ja : '必須項目が入力されていません。',
		ko : '필수 입력칸이 비어있습니다.',
		nl : 'Verplichte velden zijn leeg.',
		ro : 'Câmpurile necesare au fost lăsate goale.',
		ru : 'Поля, необходимые для заполнения, оставлены пустыми.',
		sv : 'Obligatoriska fält har lämnats tomma.',		
		zh : '必填栏位已被留空。'
	},
	BLANK_FIELD_DIALOG : {
		en : "The missing information is highlighted in red.",
		pt : "A informação em falta está destacada em vermelho.",
		de : 'Die fehlende Information ist rot markiert.',
		es : 'La información que falta se resalta en rojo.',
		fr : 'Les informations manquantes sont surlignées en rouge.',
		hi : 'छूटी हुई जानकारी को लाल रंग में दिखाया गया है।',
		it : 'Le informazioni mancanti sono evidenziate in rosso.',
		in : 'Informasi yang hilang disorot dengan warna merah.',
		ja : '赤字で強調した部分が必要事項です。',
		ko : '빈 입력칸은 빨강색으로 표시됩니다.',
		nl : 'De ontbrekende informatie is in rood gemarkeerd.',
		ro : 'Informațiile lipsă este evidențiată în roșu.',
		ru : 'Отсутствующая информация отмечена красным.',
		sv : 'Saknad information är understruken med rött.',		
		zh : '缺少的信息以红色高亮显示。'
	},
	CLEAR_ALL_TITLE : {
		en : "clear all entries",
		pt : "limpar todos itens",
		de : 'Alle Einträge löschen',
		es : 'eliminar todos',
		fr : 'effacer toutes les entrées',
		hi : 'सभी प्रविष्टियों को साफ़ करें',
		it : 'deseleziona tutte le voci',
		in : 'hapus semua entri',
		ja : 'すべてのエントリーをクリア',
		ko : '모든 입력값 지우기',
		nl : 'verwijder alle',
		ro : 'șterge toate intrările',
		ru : 'очистить все записи',
		sv : 'rensa alla poster',		
		zh : '清除所有条目'
	},
	MEASURE_SYSTEM : {
		en : "System of measurement",
		pt : "Sistema de medição",
		de : 'Einheitensystem',
		es : 'Sistema de medición',
		fr : 'Système de mesure',
		hi : 'माप की प्रणाली',
		it : 'Sistema di misurazione',
		in : 'Sistem pengukuran',
		ja : '測定方式',
		ko : '측정 방법',
		nl : 'Meetsysteem',
		ro : 'Sistem de măsurare',
		ru : 'Система измерения',
		sv : 'Mätsystem',		
		zh : '测量系统'
	},
	MEASURE_SYSTEM_INFO : {
		en : "(height, weight etc.)",
		pt : "(peso, altura, etc.)",
		de : '(Größe, Gewicht etc.)',
		es : '(altura, peso, etc)',
		fr : '(taille, poids, etc)',
		hi : '(ऊंचाई, वजन आदि)',
		it : '(Altezza, peso, ecc)',
		in : '(tinggi, berat dll.)',
		ja : '（身長、体重など）',
		ko : '(키, 무게 등)',
		nl : '(lengte, gewicht, etc.)',
		ro : '(înălțime, greutate etc)',
		ru : '(рост, вес и т.д.)',
		sv : '(längd, vikt etc.)',		
		zh : '（身高，体重等）'
	},
	IMPERIAL : {
		en : "imperial",
		pt : "imperial",
		de : 'Angloamerikanisch',
		es : 'imperial',
		fr : 'impérial',
		hi : 'इंपेरियल',
		it : 'imperiale',
		in : 'imperial',
		ja : '英国法定標準',
		ko : '파운드법',
		nl : 'imperiaal',
		ro : 'imperial',
		ru : 'стандарт',
		sv : 'kejserlig',		
		zh : '纸张尺寸'
	},
	METRIC : {
		en : "metric",
		pt : "métrico",
		de : 'Metrisch',
		es : 'métrico',
		fr : 'métrique',
		hi : 'मीट्रिक',
		it : 'metrico',
		in : 'metrik',
		ja : 'メートル法',
		ko : '미터법',
		nl : 'metriek',
		ro : 'metric',
		ru : 'метрика',
		sv : 'metriskt',		
		zh : '公制'
	},
	SETTINGS_FEEDBACK : {
		en : "Support Forum",
		pt : "Fórum de Suporte",
		de : 'Support-Forum',
		es : 'Foro de Soporte',
		fr : 'Forum d\'aide',
		hi : 'समर्थन फोरम',
		it : 'Forum di Supporto',
		in : 'Forum Pendukung',
		ja : 'サポート掲示板',
		ko : '지원 포럼',
		nl : 'Support Forum',
		ro : 'Suport Forum',
		ru : 'Форум поддержки',
		sv : 'Stödforum',		
		zh : '支持论坛'
	},
	SETTINGS_FEEDBACK_INFO : {
		en : "Post ideas and get support",
		pt : "Poste ideias e tire dúvidas",
		de : 'Senden Sie Ideen ein und erhalten Sie Unterstützung',
		es : 'Publique su opinión y obtenga respuesta',
		fr : 'Donnez-nous des idées et obtenez de l\'aide',
		hi : 'विचार पोस्ट करें और मदद पाएँ',
		it : 'Posta idee e ottieni sostegno',
		in : 'Sampaikan ide dan dapatkan dukungan',
		ja : '意見を投稿して、サポートしてもらいましょう',
		ko : '아이디어 제공 및 지원받기',
		nl : 'Plaats ideeën en krijg support<',
		ro : 'Posta idei și obține sprijin',
		ru : 'Поделитесь своими идеями и получите помощь',
		sv : 'Posta idéer och få stöd',		
		zh : '发表观点，并获得支持'
	},
	SETTINGS_REVIEW : {
		en : "Rate this App",
		pt : "Avalie este App",
		de : 'Diese App bewerten',
		es : 'Valore esta Aplicación',
		fr : 'Évaluer cette appli',
		hi : 'इस अनुप्रयोग को रेट करें',
		it : 'Vota questa applicazione',
		in : 'Nilai aplikasi ini',
		ja : 'このアプリを評価する',
		ko : '앱 평가하기',
		nl : 'Beoordeel deze App',
		ro : 'Evaluați acest App',
		ru : 'Оцените данное приложение',
		sv : 'Betygsätt den här appen',		
		zh : '为该应用程序评分'
	},
	SETTINGS_REVIEW_INFO : {
		en : "Your opinion is important to us",
		pt : "Sua opinião é importante para nós",
		de : 'Ihre Meinung ist uns wichtig',
		es : 'Su opinión es importante para nosotros',
		fr : 'Nous accordons de l\'importance à votre opinion',
		hi : 'आपका विचार हमारे लिए महत्वपूर्ण है',
		it : 'La tua opinione è importante per noi',
		in : 'Pendapat Anda penting bagi kami',
		ja : '貴重なご意見として承ります',
		ko : '여러분의 의견은 소중합니다.',
		nl : 'Jouw mening is belangrijk voor ons',
		ro : 'Opinia dumneavoastră este importantă pentru noi',
		ru : 'Ваше мнение важно для нас.',
		sv : 'Din åsikt är viktig för oss',		
		zh : '你的意见对我们很重要'
	},	
	SETTINGS_BACKUP : {
		en : "Automatic Backup",
		pt : "Backup Automático",
		de : 'Automatische Sicherung',
		es : 'Copia de seguridad automática',
		fr : 'Sauvegarde automatique',
		hi : 'स्वचालित बैकअप',
		it : 'Backup automatico',
		in : 'Rekam Cadang Otomatis',
		ja : '自動バックアップ',
		ko : '자동 백업',
		nl : 'Automatische backup',
		ro : 'Backup Automat',
		ru : 'Автоматическое резервное копирование',
		sv : 'Automatisk backup',		
		zh : '自动备份'
	},
	SETTINGS_BACKUP_INFO : {
		en : "Keep your data safe and synced",
		pt : "Mantenha seus dados seguros e sincronizados",
		de : 'Halten Sie Ihre Daten sicher und synchron',
		es : 'Mantenga sus datos seguros y sincronizados',
		fr : 'Gardez vos données sécurisées et synchronisées',
		hi : 'अपना डेटा सुरक्षित और सिंक किया गया रखें',
		it : 'Mantieni i tuoi dati al sicuro e sincronizzati',
		in : 'Amankan data Anda dan sinkronisasikan',
		ja : 'データを安全に保存して同期してください',
		ko : '데이터를 안전하게 동기화하세요.',
		nl : 'Houd uw gegevens veilig en gesynchroniseerd',
		ro : 'Menține datele în siguranță și sincronizate',
		ru : 'Храните ваши данные в безопасности и синхронизируйте их',
		sv : 'Håll dina uppgifter säkra och synkade',		
		zh : '保持你的数据安全并同步'
	},
	SETTINGS_BACKUP_INFO_LOGGED_AS : {
		en : "Logged in as ",
		pt : "Conectado como ",
		de : 'Angemeldet als ',
		es : 'Conectado como ',
		fr : 'Connecté en tant que ',
		hi : 'के रूप में लॉग इन ',
		it : 'Collegato come ',
		in : 'Masuk sebagai ',
		ja : 'としてログイン中 ',
		ko : '로그인 ',
		nl : 'Ingelogd als ',
		ro : 'conectat ca ',
		ru : 'Зашли как ',
		sv : 'Inloggad som ',		
		zh : '登入身份为 '
	},
	LOGOUT_TITLE : {
		en : "Turn off automatic backup",
		pt : "Desativar backup automático",
		de : 'Automatische Sicherung deaktivieren',
		es : 'Desactivar copia de seguridad automática',
		fr : 'Désactiver la sauvegarde automatique',
		hi : 'स्वचालित बैकअप बंद करें',
		it : 'Disattiva il backup automatico',
		in : 'Nonaktifkan pencadangan otomatis',
		ja : '自動バックアップをオフにする',
		ko : '자동 백업 끄기',
		nl : 'Zet automatische backup uit',
		ro : 'Dezactivați backup automat',
		ru : 'отключить автоматическое резервное копирование',
		sv : 'Stäng av automatisk backup',		
		zh : '关闭自动备份'
	},	
	LAST_SYNC : {
		en : "last sync",
		pt : "última sincronização",
		de : 'Letzte Synchronisierung',
		es : 'última sincronización',
		fr : 'dernière synchronisation',
		hi : 'अंतिम समन्वयन',
		it : 'ultima sincronizzazione',
		in : 'sinkronisasi terakhir',
		ja : '前回の同期',
		ko : '마지막 동기화',
		nl : 'laatste synchronisatie',
		ro : 'ultima sincronizare',
		ru : 'Последняя синхронизация',
		sv : 'senaste synkning',		
		zh : '上次同步'
	},
	SETTINGS_HELP : {
		en : "Help",
		pt : "Ajuda",
		de : 'Hilfe',
		es : 'Ayuda',
		fr : 'Aide',
		hi : 'मदद',
		it : 'Aiuto',
		in : 'Bantuan',
		ja : 'ヘルプ',
		ko : '도움말',
		nl : 'Help',
		ro : 'Ajuta',
		ru : 'Помощь',
		sv : 'Hjälp',		
		zh : '帮助'
	},
	SETTINGS_HELP_INFO : {
		en : "Topics to help you get started",
		pt : "Respostas para as dúvidas frequentes",
		de : 'Themen, die Ihnen den Einstieg erleichtern',
		es : 'Temas que le ayudarán a empezar',
		fr : 'Sujets pour bien démarrer',
		hi : 'आपको आरंभ में मदद करने के लिए विषय',
		it : 'Argomenti per aiutarti a iniziare',
		in : 'Topik untuk membantu Anda memulai',
		ja : '開始に役立つトピックス',
		ko : '시작 도움말',
		nl : 'Onderwerpen om je op gang te helpen',
		ro : 'Răspunsuri la întrebări frecvente',
		ru : 'Инструкции для начала работы',
		sv : 'Ämnen som hjälper dig att komma igång',		
		zh : '帮助你开始的话题'
	},
	SETTINGS_CONTACT : {
		en : "Contact us",
		pt : "Contato",
		de : 'Kontakt',
		es : 'Contáctenos',
		fr : 'Nous contacter',
		hi : 'हमसे संपर्क करें',
		it : 'Contattaci',
		in : 'Hubungi kami',
		ja : 'お問い合わせ',
		ko : '개발자',
		nl : 'Neem contact op met ons',
		ro : 'Contactaţi-ne',
		ru : 'Связаться с нами',
		sv : 'Kontakta oss',		
		zh : '联系我们'
	},
	SETTINGS_ABOUT : {
		en : "About",
		pt : "Sobre",
		de : 'Über',
		es : 'Acerca de',
		fr : 'À propos',
		hi : 'के बारे में',
		it : 'Informazioni',
		in : 'Tentang',
		ja : '約',
		ko : '소개',
		nl : 'Over',
		ro : 'Despre',
		ru : 'О нас',
		sv : 'om oss',		
		zh : '关于'
	},
	MALE : {
		en : "male",
		pt : "masculino",
		de : 'männlich',
		es : 'masculino',
		fr : 'homme',
		hi : 'पुरुष',
		it : 'maschio',
		in : 'pria',
		ja : '男性',
		ko : '남성',
		nl : 'mannelijk',
		ro : 'masculin',
		ru : 'мужской',
		sv : 'man',		
		zh : '男'
	},
	FEMALE : {
		en : "female",
		pt : "feminino",
		de : 'weiblich',
		es : 'femenino',
		fr : 'femme',
		hi : 'महिला',
		it : 'femmina',
		in : 'wanita',
		ja : '女性',
		ko : '여성',
		nl : 'vrouwelijk',
		ro : 'femeie',
		ru : 'женский',
		sv : 'kvinna',		
		zh : '女'
	},
	YOUR_GENDER : {
		en : "Your gender",
		pt : "Gênero",
		de : 'Ihr Geschlecht',
		es : 'Su género',
		fr : 'Votre sexe',
		hi : 'अपने सेक्स',
		it : 'Il tuo sesso',
		in : 'Jenis kelamin Anda',
		ja : '性別',
		ko : '성별',
		nl : 'Je sexe',
		ro : 'Sexul dvs.',
		ru : 'Ваш пол',
		sv : 'Ditt kön',		
		zh : '你的性别'
	},
	YOUR_HEIGHT : {
		en : "Your height",
		pt : "Altura",
		de : 'Ihre Körpergröße',
		es : 'Su altura',
		fr : 'Votre taille',
		hi : 'आपकी ऊंचाई',
		it : 'La tua altezza',
		in : 'Tinggi badan Anda',
		ja : '身長',
		ko : '키',
		nl : 'Je lengte',
		ro : 'Înălţimea Dvs.',
		ru : 'Ваш рост',
		sv : 'din längd',		
		zh : '你的身高'
	},
	YOUR_WEIGHT : {
		en : "Your weight",
		pt : "Peso",
		de : 'Ihr Gewicht',
		es : 'Su peso',
		fr : 'Votre poids',
		hi : 'आपका वजन',
		it : 'Il tuo peso',
		in : 'Berat badan Anda',
		ja : '体重',
		ko : '몸무게',
		nl : 'Je gewicht',
		ro : 'Greutatea dvs.',
		ru : 'Ваш вес',
		sv : 'Din vikt',		
		zh : '你的体重'
	},
	YOUR_AGE : {
		en : "Your age",
		pt : "Idade",
		de : 'Ihr Alter',
		es : 'Su edad',
		fr : 'Votre âge',
		hi : 'आपकी उम्र',
		it : 'La tua età',
		in : 'Usia Anda',
		ja : '年齢',
		ko : '나이',
		nl : 'Je leeftijd',
		ro : 'Varsta ta',
		ru : 'Ваш возраст',
		sv : 'Din ålder',		
		zh : '你的年龄'
	},
	YOUR_ACTIVITY : {
		en : "Your Activity",
		pt : "Nível de atividade",
		de : 'Ihre Aktivität',
		es : 'Su Actividad',
		fr : 'Votre activité',
		hi : 'अपनी गतिविधि',
		it : 'La tua attività',
		in : 'Aktivitas Anda',
		ja : 'アクティビティ',
		ko : '활동',
		nl : 'Je activiteit',
		ro : 'Activitatea dumneavoastră',
		ru : 'Ваша деятельность',
		sv : 'Din aktivitet',		
		zh : '你的活动状态'
	},
	YOUR_ACTIVITY_OPTION1 : {
		en : "Sedentary: Mostly sitting down (desk job, designer)",
		pt : "Sedentário: Quase sempre sentado (designer, escritor)",
		de : 'Bewegungsmangel: Meistens sitzend (Schreibtisch-Job, Designer)',
		es : 'Sedentario: principalmente sentado (trabajo de oficina, diseñador)',
		fr : 'Sédentaire : surtout assis (emploi de bureau, designer)',
		hi : 'आसीन: ज्यादातर बैठे रहना (डेस्क का काम, डिजाइनर)',
		it : 'Sedentario: Principalmente seduto (lavoro d\'ufficio, designer)',
		in : 'Kurang Gerak: Lebih sering duduk (kerja di depan komputer, desainer)',
		ja : 'あまり体を動かさない:大抵座っている（事務職、デザイナー）',
		ko : '정적: 거의 앉아 있음(사무직, 디자이너)',
		nl : 'Sedentair: Zit meestal (kantoorbaan, ontwerper)',
		ro : 'Sedentar: Aproape sta jos (de locuri de muncă de birou, proiectant)',
		ru : 'Сидячий образ жизни : в основном в положении сидя (работа за компьютером, дизайнер)',
		sv : 'Stillasittande: sitter för det mesta (skrivbordsjobb, designer)',		
		zh : '固定不动：大部分是坐着（办公室工作，设计师）'
	},
	YOUR_ACTIVITY_OPTION2 : {
		en : "Lightly Active: Occasionally sitting (teacher, salesman)",
		pt : "Pouco Ativo: Ocasionalmente sentado (professor, vendedor)",
		de : 'Leicht aktiv: Gelegentlich sitzend (Lehrer, Verkäufer)',
		es : 'Ligeramente activo: se sienta de vez en cuando (profesor, vendedor)',
		fr : 'Moyennement actif : parfois assis (enseignant, vendeur)',
		hi : 'थोड़ा सक्रिय: कभी कभी बैठना (शिक्षक, विक्रेता)',
		it : 'Leggermente attivo: Di tanto in tanto si siede (insegnante, venditore)',
		in : 'Lumayan Aktif: Kadang duduk (guru, penjual)',
		ja : '少し活動的：時々座る（教師、セールスマン）',
		ko : '약간 활동적: 가끔 앉음(선생님, 영업사원)',
		nl : 'Licht Actief: Af en toe zitten (leraar, verkoper)',
		ro : 'Ușor Activ: Ocazional ședinței (profesor, vânzător)',
		ru : 'Небольшая активность: иногда сидячая (преподаватель, продавец)',
		sv : 'Lätt aktiv: sitter då och då (lärare, försäljare)',		
		zh : '稍微活动：偶尔坐着（教师，销售人员）'
	},
	YOUR_ACTIVITY_OPTION3 : {
		en : "Active: Walking most of the time (waitress, mailman)",
		pt : "Ativo: Caminhando quase sempre (carteiro, garçonete)",
		de : 'Aktiv: Meistens laufend (Bedienung, Briefträger)',
		es : 'Activo: camina la mayor parte del tiempo (camarera, cartero)',
		fr : 'Actif : en mouvement la plupart du temps (serveur, facteur)',
		hi : 'सक्रिय: ज्यादातर चलते रहना (वेट्रेस, डाकिया)',
		it : 'Attivo: In movimento la maggior parte del tempo (cameriera, postino)',
		in : 'Aktif: Selalu berjalan (pelayan, tukang surat)',
		ja : '活動的：大抵歩いている（ウエイトレス、郵便配達人）',
		ko : '활동적: 거의 걸어다님(웨이트리스, 집배원)',
		nl : 'Actief: Loopt meestal (serveerster, postbode)',
		ro : 'Activ: Plimbare cele mai multe ori (chelneriță, poștaș)',
		ru : 'Активная: большая часть времени в движении (официант, почтальон)',
		sv : 'Aktiv: går omkring större delen av tiden (servitris, brevbärare)',		
		zh : '活跃的：大部分时间都在走动（服务员，邮差）'
	},
	YOUR_ACTIVITY_OPTION4 : {
		en : "Very Active: Physically hard work (construction worker)",
		pt : "Muito Ativo: Trabalho fisicamente extenuante (pedreiro, carregador)",
		de : 'Sehr aktiv: Körperlich harte Arbeit (Bauarbeiter)',
		es : 'Muy activo: trabajo físico duro (trabajador de la construcción)',
		fr : 'Très actif : emploi très physique (travailleur du bâtiment)',
		hi : 'बहुत सक्रिय: शारीरिक रूप से मुश्किल काम (निर्माण मजदूर)',
		it : 'Molto attivo: Lavoro duro dal punto di vista fisico (operaio edile)',
		in : 'Sangat Aktif: Bekerja keras secara fisik (pekerja konstruksi)',
		ja : '非常に活動的：重労働（建設作業員）',
		ko : '아주 활동적: 육체노동(건설노동자)',
		nl : 'Erg Actief: Fysiek zwaar werk (bouwvakker)',
		ro : 'Foarte activă: lucru fizic greu (muncitor în construcții)',
		ru : 'Очень активная: тяжёлый физический труд (строитель)',
		sv : 'Mycket aktiv: fysiskt hårt arbete (byggnadsarbetare)',		
		zh : '非常活跃：繁重的体力劳动者（建筑工人）'
	},
	KEEP_WEIGHT : {
		en : "Keep current weight:",
		pt : "Manter peso atual:",
		de : 'Aktuelles Gewicht halten:',
		es : 'Mantener peso actual:',
		fr : 'Conserver le poids actuel:',
		hi : 'वर्तमान वजन बनाए रखें:',
		it : 'Mantieni il peso attuale:',
		in : 'Pertahankan berat badan saat ini:',
		ja : '現在の体重を維持する：',
		ko : '현재 몸무게 유지:',
		nl : 'Behoud huidig gewicht:',
		ro : 'Păstra greutatea curent:',
		ru : 'Держите текущий вес:',
		sv : 'Håll aktuell vikt:',		
		zh : '保持当前体重：'
	},
	LOSE_WEIGHT : {
		en : "Lose weight by:",
		pt : "Perder peso:",
		de : 'Abnehmen bis:',
		es : 'Bajar peso en:',
		fr : 'Perdre du poids avant le:',
		hi : 'वजन कम:',
		it : 'Perdi peso:',
		in : 'menurunkan berat badan:',
		ja : 'キロ体重を落とす：',
		ko : '감량:',
		nl : 'gewichtsverlies:',
		ro : 'Pierde in greutate:',
		ru : 'сбросить вес с помощью:',
		sv : 'gå ner i vikt:',		
		zh : '用什么样的方式来减肥：'
	},
	GAIN_WEIGHT : {
		en : "Gain weight by:",
		pt : "Ganhar peso:",
		de : 'Zunehmen bis:',
		es : 'Aumentar peso en:',
		fr : 'Prendre du poids avant le:',
		hi : 'भार में बढ़ना:',
		it : 'Prendi peso:',
		in : 'bertambah berat:',
		ja : 'キロ体重を増やす：',
		ko : '증가:',
		nl : 'gewichtstoename:',
		ro : 'Creștere în greutate:',
		ru : 'набрать вес с помощью:',
		sv : 'gå upp i vikt:',		
		zh : '用什么样的方式来增胖：'
	},
	PER_WEEK : {
		en : "per week",
		pt : "por semana",
		de : 'pro Woche',
		es : 'por semana',
		fr : 'par semaine',
		hi : 'प्रति सप्ताह',
		it : 'a settimana',
		in : 'per minggu',
		ja : '1週間に',
		ko : '주당',
		nl : 'per week',
		ro : 'pe săptămână',
		ru : 'в неделю',
		sv : 'per vecka',		
		zh : '每周'
	},
	HELP_TOPICS_ARRAY : {
		////////////
		en : { //
			////////////
			"Getting started" : "\
				<p>Your body does not restart its calories every 24 hours, so why should your calorie counter? MyLiveDiet simulates the way the body actually uses energy, giving you a more realistic, real-time feedback.</p>\
				<p>First, fill your profile data. Based on this information, the app will calculate how many calories you need in order to keep your current weight.</p>\
				<p>Then you should define a weight loss rate, given in lb/kg per week.</p>\
				<p>The resulting value will include the necessary caloric restriction for you to achieve that goal.</p>\
				<p>Now hit start, and the app will show how many calories you have burned over time, so you'll always know exactly how many calories you should consume at any given moment - with the caloric restriction calculation already included.</p>\
				<p>For instance:</p>\
				<p>2400 per day / 24 hours = 100 calories per hour</p>\
				<p>So, after 30 minutes, the counter will indicate you have “50 calories available”. Its that simple!</p>\
				<p>All you have to do is keep the counter around zero, and you will be automatically walking towards your goal!</p>\
			",
			////////////
			"The Main Counter" : "\
				<p>The main counter has 3 states: balanced (between -300 and 300, shown in blue), surplus (-300 and below, shown in red), and deficit (300 and up, shown in green).</p>\
				<p>When the counter hits +/-600, the “caloric status” block on the status screen will turn yellow to indicate you are getting too distant from the balanced state. The value 600 was chosen because it is usually the highest amount of calories recommend per meal.</p>\
				<p>Note that the counter units are given in “calories available” for the sake of simplicity, so as to quickly indicate whether you ate too much (negative values) or too little (positive values), as if you were “gaining points” over time. The actual caloric (energetic) balance of your body would be the opposite (negative for eating too little, positive for eating too much), but since this seems to reward over-eating by giving it a positive value, the “calories available” approach seemed generally preferable.</p>\
			",
			////////////
			"Changing the Start Date" : "\
				<p>The default behaviour of the app is to start counting from the moment you hit Start. If for some reason you would like to adjust that value (e.g. you started dieting this morning, but only had time to setup app in the afternoon), just tap the down arrow on the Start button to reveal the date picker.</p>\
			",
			////////////
			"Calculating Calories" : "\
				<p>The weight loss rate (kg/lb per week) is calculated using a simple formula based on the number of calories in a pound (3500) or kilogram (7700) of fat. </p>\
				<p>Let us say you need 2000 daily calories in order to keep your current weight, and you want to lose 0.5 kg per week.</p>\
				<p>Divide 7700 by 2 to get the total calories in 0.5 kg of fat:</p>\
				<p>7700 / 2 = 3850</p>\
				<p>Then divide that value by 7 to get how many daily calories you need to cut back:</p>\
				<p>3850 / 7 = 550</p>\
				<p>Now subtract that value from your daily intake:</p>\
				<p>2000 – 550 = 1450</p>\
				<p>That’s how many you have to consume daily in order to lose 0.5 kg a week.</p>\
			"
			////////////
		},
		////////////
		pt : { //
			////////////
			"Como começar?" : "\
				<p>Seu corpo não esquece as calorias a cada 24 horas, então por que seu contador de calorias deveria? MyLiveDiet simula a maneira como seu corpo realmente usa energia, fornecendo um feedback mais realístico e atualizado.</p>\
				<p>Primeiro, preencha seu perfil. Com base nessa informação, o aplicativo calculará quantas calorias você precisa para manter seu peso atual.</p>\
				<p>Depois você deve definir a perda de peso (em kg por semana).</p>\
				<p>O valor resultante incluirá a restrição calórica necessária para que você atinja esse objetivo.</p>\
				<p>Agora pressione Iniciar, e o aplicativo passará a mostrar quantas calorias você queimou ao longo do tempo, e assim você saberá sempre quantas calorias deve consumir - já estando incluso nesse valor o cálculo da restrição calórica.</p>\
				<p>Por exemplo:</p>\
				<p>2400 calorias por dia / 24 horas = 100 calorias por hora</p>\
				<p>Então, após 30 minutos, o contador indicará que você possui “50 calorias disponíveis”. É simples assim!</p>\
				<p>Você só precisa manter o contador em torno de zero, e estará automaticamente caminhando em direção ao seu objetivo!</p>\
			",
			////////////
			"O Contador Principal" : "\
				<p>O contador principal possui 3 estados: balanceado (entre -300 e 300, mostrado em azul), excesso (-300 e abaixo, mostrado em vermelho), e deficit (300 e acima, mostrado em verde). </p>\
				<p>Quando o contador chega em +/-600, o bloco “status calórico” na tela de status fica amarelo para indicar que você está distanciando-se demais do balanço calórico ideal (zero). O valor 600 foi escolhido porque esse é geralmente o número máximo de calorias recomendado por refeição.</p>\
				<p>Note que o contador utiliza “calorias disponíveis” como medida por questão de praticidade, para indicar rapidamente se você comeu demais (valores negativos) ou de menos (valores positivos), como se estivesse “ganhando pontos” com o passar do tempo. O balanço calórico (energético) real de seu corpo seria o oposto (negativo para comer pouco, positivo para comer demais), mas isso parece recompensar o consumo excessivo de calorias, de modo que o esquema de “calorias disponíveis” pareceu preferível.</p>\
			",
			////////////
			"Mudar Data Inicial" : "\
				<p>O comportamento padrão do aplicativo é começar a contagem a partir do momento em que o botão Iniciar é pressionado. Porém, se por algum motivo você precisar ajustar esse valor (e.g. você começou a dieta esta manhã, mas só teve tempo de configurar o aplicativo à tarde), basta pressionar a seta para baixo (no botão Iniciar) para revelar o seletor de data.</p>\
			",
			////////////
			"Calculando Calorias" : "\
				<p>A perda de peso (em kg por semana) é calculada utilizando-se uma fórmula simples, baseada no número de calorias em um quilograma de gordura (7700).</p>\
				<p>Suponhamos que você precise de 2000 calorias por dia para manter seu peso atual, e deseja perder 0.5 kg por semana.</p>\
				<p>Divida 7700 por 2 para encontrar o total de calorias em 0.5 kg de gordura:</p>\
				<p>7700 / 2 = 3850</p>\
				<p>Depois divida esse valor por 7 para saber quantas calorias diárias você precisa reduzir:</p>\
				<p>3850 / 7 = 550</p>\
				<p>Agora subtraia esse valor de sua ingestão diária:</p>\
				<p>2000 – 550 = 1450</p>\
				<p>Esse é o número de calorias que você deve consumir diariamente para perder 0.5 kg por semana.</p>\
			"
			////////////
		}
	}
};
/////////////////////////
// fallback to english //
/////////////////////////
if(lang != "en" && lang != "pt") { 
	LANG.HELP_TOPICS_ARRAY[lang] = LANG.HELP_TOPICS_ARRAY['en'];
}

