var mi = {
	AUTO_UPDATE : {
		en : 'Automatic Update',
		pt : 'Atualizações automáticas',
		ar : '',
		bg : '',
		ca : '',
		cs : '',
		da : '',
		de : '',
		el : '',
		es : '',
		et : '',
		fa : '',
		fi : '',
		fr : '',
		hi : '',
		hr : '',
		hu : '',
		it : '',
		id : '',
		iw : '',
		ja : '',
		ko : '',
		lt : '',
		lv : '',
		ms : '',
		nl : '',
		nb : '',
		pl : '',
		ro : '',
		ru : '',
		sk : '',
		sl : '',
		sr : '',
		sv : '',
		th : '',
		tr : '',
		uk : '',
		vi : '',
		zh : '',
		zt : '',
	},
	APP_UPDATED : {
		en : 'The app has been updated.',
		pt : 'O aplicativo foi atualizado.',
		ar : '',
		bg : '',
		ca : '',
		cs : '',
		da : '',
		de : '',
		el : '',
		es : '',
		et : '',
		fa : '',
		fi : '',
		fr : '',
		hi : '',
		hr : '',
		hu : '',
		it : '',
		id : '',
		iw : '',
		ja : '',
		ko : '',
		lt : '',
		lv : '',
		ms : '',
		nl : '',
		nb : '',
		pl : '',
		ro : '',
		ru : '',
		sk : '',
		sl : '',
		sr : '',
		sv : '',
		th : '',
		tr : '',
		uk : '',
		vi : '',
		zh : '',
		zt : '',
	},
	RESTART_NOW : {
		en : 'Would you like to restart it now?',
		pt : 'Gostaria de reiniciar agora?',
		ar : '',
		bg : '',
		ca : '',
		cs : '',
		da : '',
		de : '',
		el : '',
		es : '',
		et : '',
		fa : '',
		fi : '',
		fr : '',
		hi : '',
		hr : '',
		hu : '',
		it : '',
		id : '',
		iw : '',
		ja : '',
		ko : '',
		lt : '',
		lv : '',
		ms : '',
		nl : '',
		nb : '',
		pl : '',
		ro : '',
		ru : '',
		sk : '',
		sl : '',
		sr : '',
		sv : '',
		th : '',
		tr : '',
		uk : '',
		vi : '',
		zh : '',
		zt : '',
	},
	MY_ITEMS : {
		en : '',
		pt : '',
		ar : '',
		bg : '',
		ca : '',
		cs : '',
		da : '',
		de : '',
		el : '',
		es : '',
		et : '',
		fa : '',
		fi : '',
		fr : '',
		hi : '',
		hr : '',
		hu : '',
		it : '',
		id : '',
		iw : '',
		ja : '',
		ko : '',
		lt : '',
		lv : '',
		ms : '',
		nl : '',
		nb : '',
		pl : '',
		ro : '',
		ru : '',
		sk : '',
		sl : '',
		sr : '',
		sv : '',
		th : '',
		tr : '',
		uk : '',
		vi : '',
		zh : '',
		zt : '',
	},
	MY_ITEMS : {
		en : '',
		pt : '',
		ar : '',
		bg : '',
		ca : '',
		cs : '',
		da : '',
		de : '',
		el : '',
		es : '',
		et : '',
		fa : '',
		fi : '',
		fr : '',
		hi : '',
		hr : '',
		hu : '',
		it : '',
		id : '',
		iw : '',
		ja : '',
		ko : '',
		lt : '',
		lv : '',
		ms : '',
		nl : '',
		nb : '',
		pl : '',
		ro : '',
		ru : '',
		sk : '',
		sl : '',
		sr : '',
		sv : '',
		th : '',
		tr : '',
		uk : '',
		vi : '',
		zh : '',
		zt : '',
	},
	CATEGORIES : {
		en : 'Categories',
		pt : 'Categorias',
		ar : 'الفئات',
		bg : 'Категории',
		ca : 'Categories',
		cs : 'Kategorie',
		da : 'Kategorier',
		de : 'Kategorien',
		el : 'Κατηγορίες',
		es : 'Categorías',
		et : 'Kategooriad',
		fa : 'ردههای صفحه',
		fi : 'Luokat',
		fr : 'Catégories',
		hi : 'श्रेणियाँ',
		hr : 'Kategorije',
		hu : 'Kategóriák',
		it : 'Categorie',
		id : 'Kategori',
		iw : 'קטגוריות',
		ja : 'カテゴリ',
		ko : '카테고리',
		lt : 'Kategorijos',
		lv : 'Kategorijas',
		ms : 'Kategori',
		nl : 'Categorieën',
		nb : 'Kategorier',
		pl : 'Kategorie',
		ro : 'Categorii',
		ru : 'Категории',
		sk : 'Kategórie',
		sl : 'Kategorije',
		sr : 'Категорије',
		sv : 'Kategorier',
		th : 'หมวดหมู่',
		tr : 'Kategoriler',
		uk : 'Категорії',
		vi : 'Loại',
		zh : '类别',
		zt : '類別',
	},
	BUY : {
		en : 'Free evaluation (1 week)',
		pt : 'Avaliação gratuita (1 semana)',
		ar : 'تقييم المجاني (1 أسبوع)',
		bg : 'Свободен оценяване (1 седмица)',
		ca : 'Avaluació gratuït (1 setmana)',
		cs : 'Volné Hodnocení (1 týden)',
		da : 'Gratis evaluering (1 uge)',
		de : 'Kostenlose Testversion (1 Woche)',
		el : 'Δωρεάν αξιολόγηση (1 εβδομάδα)',
		es : 'Evaluación gratuita (1 semana)',
		et : 'Tasuta hindamine (1 nädal)',
		fa : 'ارزیابی رایگان (1 هفته)',
		fi : 'Ilmainen kokeiluversio (1 viikko)',
		fr : 'Évaluation gratuite (1 semaine)',
		hi : 'मूल्यांकन संस्करण (1 सप्ताह)',
		hr : 'Besplatno evaluacija (1 tjedno)',
		hu : 'Ingyenes próbaverzió (1 hét)',
		it : 'Valutazione gratuita (1 settimana)',
		id : 'Evaluasi gratis (1 minggu)',
		iw : 'גרסה חינם הערכה (שבוע 1)',
		ja : '評価版（1週）。',
		ko : '무료 평가 (1 주)',
		lt : 'Nemokama vertinimas (1 savaitę)',
		lv : 'Bezmaksas novērtējums (1 nedēļa)',
		ms : 'Penilaian percuma (1 minggu)',
		nl : 'Gratis evaluatie (1 week)',
		nb : 'Gratis evaluering (en uke)',
		pl : 'Wolny ocena (1 tydzień)',
		ro : 'Versiune de evaluare (1 săptămână)',
		ru : 'Бесплатный оценки (1 неделя)',
		sk : 'Zadarmo hodnotenie (1 týždeň)',
		sl : 'Brezplačne ocena (1 teden)',
		sr : 'Бесплатно евалуација (1 недеља)',
		sv : 'Gratis utvärdering (1 vecka)',
		th : 'รุ่นประเมินผลฟรี (1 สัปดาห์)',
		tr : 'Ücretsiz deneme (1 hafta)',
		uk : 'Безкоштовна пробна версія (1 тиждень)',
		vi : 'Phiên bản đánh giá miễn phí (1 tuần)',
		zh : '免费试用版（1周）。',
		zt : '免費試用版（1週）。',
	},
}
//’



































