#!/bin/bash

echo " "
rm -R chronoburn-linux-x64 *.snap
echo " "

echo "#NPM"
echo " "
time npm install
echo " "

echo "#PACK"
echo " "
time electron-packager . 
echo " "

echo "#BUILD"
echo " "
echo "building snap..."
echo " "
time electron-installer-snap --src=chronoburn-linux-x64
echo " "

echo "#INSTALL"
echo " "
echo "sudo snap remove chronoburn && sudo snap install *.snap --dangerous --devmode"
echo " "

echo "#UPLOAD"
echo " "
echo "snapcraft login"
echo "time snapcraft push *.snap"
echo " "

