#!/bin/bash

echo " "
rm -R chronoburn-linux-x64 *.snap
echo " "

echo "#NPM"
echo " "
time npm install
echo " "

echo "#PACK"
echo " "
time electron-packager . 
echo " "
echo "running execstack --clear-execstack"
execstack --clear-execstack ./chronoburn-linux-x64/chronoburn
execstack --clear-execstack ./node_modules/electron/dist/electron
echo " "
echo "#BUILD"
echo " "
echo "building snap..."
echo " "
time electron-installer-snap --src=chronoburn-linux-x64
echo " "
echo "#INSTALL"
echo " "
sudo snap remove chronoburn && sudo snap install *.snap --dangerous --devmode
echo " "

echo "running chronoburn async..."
chronoburn &
echo " "

echo "#UPLOAD INSTRUCTIONS:"
echo "snapcraft login"
echo "time snapcraft push *.snap"
echo " "

